name: build-win

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Set up Windows build environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build Windows client
        working-directory: ./client
        shell: cmd
        run: cl /EHsc main.cc /Fclient.exe
